plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.15-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'com.deustoRestaurant'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

repositories {
	mavenCentral()
	maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.h2database:h2'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	
}

tasks.named('test') {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
	doLast {
		def report = file("${buildDir}/reports/tests/test/index.html")
		if (report.exists()) exec { commandLine 'cmd', '/c', 'start', report.absolutePath }
	}
}

task testUnit(type: Test) {
	description = 'Ejecuta solo los tests unitarios (@Tag("unit"))'
	group = 'verification'
	useJUnitPlatform {
		includeTags 'unit'
	}
}

task testIntegracion(type: Test) {
	description = 'Ejecuta solo los tests de integración (@Tag("integration"))'
	group = 'verification'
	useJUnitPlatform {
		includeTags 'integration'
	}
}

jacoco {
	toolVersion = "0.8.13"
}

jacocoTestReport {
	dependsOn test
	doLast {
		def report = file("${buildDir}/reports/jacoco/html/index.html")
		if (report.exists()) exec { commandLine 'cmd', '/c', 'start', report.absolutePath }
	}
	reports {
		xml.required = true
		xml.outputLocation = layout.buildDirectory.file('reports/jacoco/xml/jacocoTestReport.xml')
		html.required = true
		html.outputLocation = layout.buildDirectory.dir('reports/jacoco/html')
	}
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: [
				'**/DRestaurantApplication.class',
				'**/DataInitializer.class',
				'**/dto/**',
				'**/entity/**',
				'**/config/**'
			])
		}))
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				minimum = 0.70
			}
		}
	}
}

javadoc {
	doLast {
		def report = file("${buildDir}/docs/javadoc/index.html")
		if (report.exists()) exec { commandLine 'cmd', '/c', 'start', report.absolutePath }
	}
    options.encoding = 'UTF-8'
    options.locale = 'es'
    options.windowTitle = 'DeustoRestaurant API'
    options.docTitle = 'DeustoRestaurant - Documentación'
    options.author = true
    options.version = true
    options.addStringOption('Xdoclint:none', '-quiet')
    failOnError = false
}